2024-01-20 16:44:43,184: root: INFO: MLTrader : Executing the initialize lifecycle method
2024-01-20 16:44:44,227: root: INFO: Current backtesting datetime 2023-12-15 08:30:00-05:00
2024-01-20 16:44:44,228: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-01-20 16:44:44,229: root: INFO: Current backtesting datetime 2023-12-15 09:30:00-05:00
2024-01-20 16:44:44,229: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-01-20 16:44:44,230: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-01-20 16:44:44[0m
2024-01-20 16:44:44,234: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-01-20 16:44:44,239: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-01-20 16:44:44,239: root: ERROR: 'datetime.datetime' object has no attribute 'str'
2024-01-20 16:44:44,240: root: ERROR: Traceback (most recent call last):
  File "C:\Users\Aditya\anaconda3\envs\py310\lib\site-packages\lumibot\strategies\strategy_executor.py", line 829, in run
    self._run_trading_session()
  File "C:\Users\Aditya\anaconda3\envs\py310\lib\site-packages\lumibot\strategies\strategy_executor.py", line 780, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\Aditya\anaconda3\envs\py310\lib\site-packages\lumibot\strategies\strategy_executor.py", line 274, in func_output
    result = func_input(self, *args, **kwargs)
  File "C:\Users\Aditya\anaconda3\envs\py310\lib\site-packages\lumibot\strategies\strategy_executor.py", line 298, in func_output
    result = func_input(self, *args, **kwargs)
  File "C:\Users\Aditya\anaconda3\envs\py310\lib\site-packages\lumibot\strategies\strategy_executor.py", line 87, in func_output
    return func_input(self, *args, **kwargs)
  File "C:\Users\Aditya\anaconda3\envs\py310\lib\site-packages\lumibot\strategies\strategy_executor.py", line 378, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\Aditya\anaconda3\envs\py310\lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\Aditya\anaconda3\envs\py310\lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "c:\Coding\Stock_bot\tradingbot.py", line 52, in on_trading_iteration
    news = self.get_news()
  File "c:\Coding\Stock_bot\tradingbot.py", line 41, in get_news
    today, three_day_prior = self.get_dates()
  File "c:\Coding\Stock_bot\tradingbot.py", line 37, in get_dates
    return today.str('%Y-%m-%d'), three_days_prior.str('%Y-%m-%d')
AttributeError: 'datetime.datetime' object has no attribute 'str'

2024-01-20 16:44:44,241: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-01-20 16:44:44,247: root: INFO: Backtesting finished
2024-01-20 16:44:44,248: root: WARNING: Cannot plot returns because the strategy returns are missing
2024-01-20 16:44:44,319: root: WARNING: Cannot create a tearsheet because the strategy returns are missing
2024-01-20 16:44:44,319: backtest_stats: INFO: Backtest took 0:00:01.135653 for a speed of 0.000
